//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int id_task { get; set; }
        public string title { get; set; }
        public string descr { get; set; }
        public Nullable<int> asigned_to { get; set; }
        public int id_list { get; set; }
    
        public virtual List List { get; set; }
    }
}
